Repository nextcloud/files_accesscontrol, pull requests merged in 2020-09, with the labels that each got.

#163 Do not set retry flag on ForbiddenException
  lib/Operation.php
Labels: 3. to review, bug

#164 adapt to ibootstrap
  appinfo/app.php
  lib/AppInfo/Application.php
  lib/Listener/FlowRegisterOperationListener.php
Labels: 3. to review, enhancement

#173 Fix path in shared storages
  lib/Operation.php
Labels: 3. to review, backport-request, bug
