Repository nextcloud/files_accesscontrol, pull requests merged in 2022-08, with the labels that each got.

#250 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#249 [stable24] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#248 don't exclude shared storage from wrapper
  lib/AppInfo/Application.php
Labels: 3. to review

#254 1.14.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#255 1.13.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#256 v1.12.2
  appinfo/info.xml
Labels: 3. to review

#257 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#261 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#260 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies
