Repository nextcloud/files_accesscontrol, pull requests merged in 2022-09, with the labels that each got.

#263 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#264 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#265 add property types, fix deprecations
  lib/CacheWrapper.php
  lib/Listener/FlowRegisterOperationListener.php
  lib/Operation.php
Labels: 3. to review, technical debt

#267 Adjust testing matrix for Nextcloud 25 on stable25
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-christophwurst-nextcloud.yml
Labels: 4. to release

#268 Add Nextcloud 26 support on master
  .github/workflows/update-christophwurst-nextcloud.yml
  appinfo/info.xml
Labels: 4. to release

#266 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies
