Repository nextcloud/files_accesscontrol, pull requests merged in 2023-05, with the labels that each got.

#350 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#358 [stable25] fix: Check before writing if writing without a part file
  lib/StorageWrapper.php
  tests/Integration/composer.json
  tests/Integration/composer.lock
  tests/Integration/features/author.feature
  tests/Integration/features/bootstrap/WebDav.php
Labels: bug, 3. to review

#355 [stable26] fix(filename): Exclude part/transfer files from checks
  lib/Operation.php
  tests/Integration/data/dosexecutable.exe
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/bootstrap/WebDav.php
  tests/Integration/features/filename.feature
Labels: 3. to review

#361 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#363 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#362 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#372 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#370 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#371 [stable24] Update nextcloud/ocp dependency
  .github/workflows/phpunit-pgsql.yml
  composer.lock
Labels: 3. to review, dependencies
