Repository nextcloud/files_accesscontrol, pull requests merged in 2023-09, with the labels that each got.

#416 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#417 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#385 reuse the cache entry we already have when doing rule checking
  lib/CacheWrapper.php
  lib/Operation.php
  lib/StorageWrapper.php
Labels: 3. to review

#428 fix(autoloader): Fix dev autoloader overwriting OCP
  composer.json
Labels: 4. to release
