Repository nextcloud/files_accesscontrol, pull requests merged in 2023-03, with the labels that each got.

#313 chore: Add Nextcloud 27 support on master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
Labels: 4. to release

#316 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#315 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#302 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#298 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#319 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#317 Start integration tests
  .github/dependabot.yml
  .github/workflows/integration.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .gitignore
  composer.json
  tests/Integration/app/appinfo/info.xml
  tests/Integration/app/appinfo/routes.php
  tests/Integration/app/lib/Controller/EndpointController.php
  tests/Integration/composer.json
  tests/Integration/composer.lock
  tests/Integration/config/behat.yml
  tests/Integration/data/textfile-2.txt
  tests/Integration/data/textfile.txt
  tests/Integration/features/author.feature
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/bootstrap/WebDav.php
  tests/Integration/features/manage-workflows.feature
  tests/Integration/features/sharing-user.feature
  tests/Integration/run.sh
  tests/Unit/StorageWrapperTest.php
  tests/phpunit.xml
Labels: enhancement, 3. to review

#323 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#322 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#320 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#324 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#310 fix: Check before writing if writing without a part file
  lib/StorageWrapper.php
  tests/Integration/composer.json
  tests/Integration/composer.lock
  tests/Integration/features/author.feature
  tests/Integration/features/bootstrap/WebDav.php
Labels: bug, 3. to review
