Repository nextcloud/files_accesscontrol, pull requests merged in 2023-08, with the labels that each got.

#396 [master] Update nextcloud/ocp dependency
  .github/workflows/phpunit-mysql.yml
  composer.lock
Labels: 3. to review, dependencies

#398 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#397 [stable25] Update nextcloud/ocp dependency
  .github/workflows/appstore-build-publish.yml
  .github/workflows/integration.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  composer.lock
Labels: 3. to review, dependencies

#402 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#404 fix(CI): Fix nextcloud/ocp package
  composer.json
  composer.lock
Labels: bug, 3. to review

#405 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#408 chore: Release 1.15.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#409 chore: Release 1.16.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#413 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#412 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
