Repository nextcloud/files_accesscontrol, pull requests merged in 2023-04, with the labels that each got.

#334 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#335 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#333 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#330 fix(filename): Exclude part/transfer files from checks
  lib/Operation.php
  tests/Integration/data/dosexecutable.exe
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/bootstrap/WebDav.php
  tests/Integration/features/filename.feature
Labels: bug, 3. to review

#337 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#341 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#343 return of `current()` may be false
  lib/Operation.php
Labels: bug, 3. to review, backport-request

#347 Update appstore-build-publish.yml to latest
  .github/workflows/appstore-build-publish.yml
Labels: bug, 3. to review, backport-request

#352 [stable25] Update appstore-build-publish.yml to latest
  .github/workflows/appstore-build-publish.yml
Labels: bug, 3. to review, backport-request
