Repository nextcloud/files_accesscontrol, pull requests merged in 2023-07, with the labels that each got.

#386 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#387 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#391 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#392 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#393 Make integration tests more reliable by skipping GARM for now
  .github/workflows/integration.yml
Labels: bug, 3. to review

#321 tests: Add test for mimetype blocking on share
  tests/Integration/data/code.js
  tests/Integration/data/hello
  tests/Integration/data/nc.exe
  tests/Integration/data/nextcloud.pdf
  tests/Integration/features/bootstrap/WebDav.php
  tests/Integration/features/mimetypes.feature
  tests/Integration/features/sharing-user.feature
Labels: 3. to review

#394 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#395 Update nextcloud/ocp and its dependencies
  composer.lock
Labels: 3. to review, dependencies
