Repository nextcloud/files_accesscontrol, pull requests merged in 2024-05, with the labels that each got.

#526 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#522 fix(wrapper): Correctly handle directories
  lib/StorageWrapper.php
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/bootstrap/WebDav.php
  tests/Integration/features/mimetypes.feature
  tests/Unit/StorageWrapperTest.php
Labels: bug, 3. to review, backport-request

#529 [stable27] fix(wrapper): Correctly set the flag whether entry is a directory
  lib/StorageWrapper.php
  tests/Integration/data/code.js
  tests/Integration/data/hello
  tests/Integration/data/nc.exe
  tests/Integration/data/nextcloud.pdf
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/bootstrap/WebDav.php
  tests/Integration/features/mimetypes.feature
  tests/Integration/features/sharing-user.feature
  tests/Unit/StorageWrapperTest.php
Labels: bug, 3. to review

#533 Add SPDX header
  .github/workflows/reuse.yml
  .reuse/dep5
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  Makefile
  README.md
  appinfo/info.xml
  img/app-dark.svg
  img/app.svg
  lib/AppInfo/Application.php
  lib/CacheWrapper.php
  lib/Listener/FlowRegisterOperationListener.php
  lib/Operation.php
  lib/StorageWrapper.php
Labels: 3. to review, technical debt

#534 Fix warnings from reuse
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/integration.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  .php-cs-fixer.dist.php
  .reuse/dep5
  AUTHORS.md
  js/admin.js
  tests/Integration/app/appinfo/info.xml
  tests/Integration/app/appinfo/routes.php
  tests/Integration/app/lib/Controller/EndpointController.php
  tests/Integration/config/behat.yml
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/bootstrap/WebDav.php
  tests/Integration/run.sh
  tests/Unit/StorageWrapperTest.php
  tests/bootstrap.php
Labels: bug, 3. to review

#537 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#535 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#536 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#538 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#539 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#540 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#541 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
