Repository nextcloud/files_accesscontrol, pull requests merged in 2024-10, with the labels that each got.

#608 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#610 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#609 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#611 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#614 chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: dependencies

#616 ci: Fix missing GD package
  .github/workflows/integration.yml
Labels: backport-request

#615 [stable30] chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: dependencies

#620 feat(tests): Add integration test for file system tags
  tests/Integration/app/appinfo/routes.php
  tests/Integration/app/lib/Controller/EndpointController.php
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/sharing-user.feature
Labels: 3. to review, backport-request

#625 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#626 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#627 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
