Repository nextcloud/files_accesscontrol, pull requests merged in 2024-07, with the labels that each got.

#559 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#560 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#562 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#563 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#564 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#561 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#566 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#567 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#568 fix: make access denied message a bit clearer
  lib/Operation.php
Labels: 3. to review

#573 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#574 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#572 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#571 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#576 Migrate dep5 to toml
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt
