Repository nextcloud/files_accesscontrol, pull requests merged in 2025-02, with the labels that each got.

#662 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#664 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#663 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#665 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/integration.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies

#666 ci: Add a summary for integration
  .github/workflows/integration.yml
  lib/Operation.php
Labels: 3. to review

#668 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#669 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#670 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#676 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#674 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#675 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#673 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#680 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#679 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#682 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#681 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
